version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "chore(deps)"
    groups:
       deps:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
    assignees:
      - "jorgepiloto"
    commit-message:
      prefix: "ci"
    groups:
       actions:
          patterns:
            - "*"
